name: microsoft_store_upgrader
description: "Microsoft store upgrader implementation."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2


flutter:
  plugin:
    platforms:
      windows:
        pluginClass: MicrosoftStoreUpgraderPlugin
